spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JavaBoby/config-repo.git
          username: JavaBoby
          password: 1332119@niu
          basedir: D:/idearworkspace/config/basedir
server:
  port: 7070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"